### ISSUE TITLE
Docker logs

### ISSUE THREAD

**Issue by MajoV** [oznu/docker-unms#1]
@oznu 
I am testing unms:armhf and everyday at 5:00 I have in logs this kind of message

![ol](https://user-images.githubusercontent.com/26937202/33358813-394d5da6-d4cb-11e7-8360-54fd993d8da0.PNG)

UNMS works well, Is it important for me?
thank you Majo

**Comment by oznu** [comment]
As far as I can tell the UNMS app does nothing with the logging container except check that it's up  and running:

```js
/*
 * Periodically check if fluentd is running and logs a message if not
 */
const pingFluentd = () =>
  execFile('sh', ['-c', `nc -z ${config.fluentdHost} ${config.fluentdPort}`])
    .catch((error) => {
      logging.error(`Unable to reach ${config.fluentdHost}:${config.fluentdPort}`, error);
      logFluentdPingFailed(config.fluentdHost, config.fluentdPort);
    });
```

**Comment by oznu** [comment]
You can probably suppress the error by setting `-e UNMS_FLUENTD_PORT=8080` or `-e UNMS_FLUENTD_PORT=80` if your running 0.11.0 or higher since the internal ports will change from this release.

**Comment by MajoV** [comment]
@oznu 
Thank you for your support. I omit all betas and wait for armhf version 0.11.0. One error message per day does not matter to me.

**Comment by MajoV** [comment]
@oznu 
After update to 0.11.0, no more these error logs.
Thank you
