### ISSUE TITLE
Exposed HTTP port 

### ISSUE THREAD

**Issue by Jensen95** [oznu/docker-unms#11]
Hi, is it just me or is there something not forwarded correctly on port 80?
I have tried on my computer and my server to run the image and none of them accesses the exposed port.

When I try the HTTPS port I get an error `400 Bad Request The plain HTTP request was sent to HTTPS port`
Is this the intended behaviour, because if I use 8081 it works like a charm 🙂

**Comment by oznu** [comment]
Hi @Jensen95,

What does your docker run command look like when you get `400 Bad Request`?

**Comment by Jensen95** [comment]
In both cases, I'm just rolling with the default, so I can't give you a specific docker command

- **My PC:** I'm running the container through Kitematic that binds the exposed port to some localhost port(usually at 277xx range and forward) 
- **My Server:** Deployed with Dokku defaults to exposing the `EXPOSE` part of the Dockerfile and it's then linking it to the container.

Both cases got solved by forwarding HTTP request to port 8081 instead of 80 and 443.
Should there be any difference doing it this way?

****
So on the server, I have the forwarding working with:

`DOKKU_PROXY_PORT_MAP:  http:80:8081 https:443:8081`

Default made from Dockerfile:

`DOKKU_PROXY_PORT_MAP:  http:443:443 http:80:80` 

I also tried `DOKKU_PROXY_PORT_MAP:  http:80:80` but that didn't work either

**Comment by oznu** [comment]
Port 80 will just attempt to redirect to port 443 - or whatever your `PUBLIC_HTTPS_PORT` variable is set to.

See the source code in the upstream repo:

https://github.com/Ubiquiti-App/UNMS/blob/master/src/nginx/nginx.conf.template#L140-L150

I run my setup behind another nginx proxy (that handles all my apps) and my upstream server is set to `https://unms:443` which works fine. The `400` error you go suggests Dokku wasn't proxying the request to the upstream as https.

**Comment by Jensen95** [comment]
Doh, thanks man 😃
In  Dokku was proxy_pass was set to `http` and not `https`
The local problem was simply me not writing `https://localhost:PORT`
