### ISSUE TITLE
Reverse proxy setup

### ISSUE THREAD

**Issue by bjonness406** [oznu/docker-unms#13]
Hey, I could use some help with reverse proxy and unms if you have the chance. 

I have set it up behind a nginx proxy and connecting fine on the unms webpage.
But I am having some troubles connecting my edgemax devices to unms behind the reverse proxy.

Could you be so kind to share your nginx site config, your port forwards on the router and your docker run command to help me out?

**Comment by oznu** [comment]
Hi @bjonness406,

My setup probably won't help you unfortunately. I only use a reverse proxy to access the UNMS webpage instance remotely, all my ubnt edge devices connect to the unms directly over a private subnet.

**Comment by bjonness406** [comment]
I think the problem is that I want to set another inform port than the standard. 
I have tried to change -e PUBLIC_HTTPS_PORT=8082 and -e PUBLIC_WS_PORT=8082, but my edgemax devices will not connect to unms on port 8082. If I change the port on the Unms key to 443 from 8082 I get connected. 

Is there a way to change the --ws-port on this docker? If not, is there any chance you could add this? Would be awsome.

"Use installation script argument --ws-port <NUMBER> to configure the UNMS WebSocket server to use a separate port for communication with your devices."
https://help.ubnt.com/hc/en-us/articles/360000119728-UNMS-Optional-Installation-Steps#6

**Comment by oznu** [comment]
Have you tried it like this?

```
docker run -e PUBLIC_WS_PORT=8082 --e PUBLIC_HTTPS_PORT=8082 -p 8082:443 oznu/unms
```

**Comment by bjonness406** [comment]
yes, I have tried
`docker run -e PUBLIC_WS_PORT=8082 --e PUBLIC_HTTPS_PORT=8082 -p 443:443 oznu/unms`

Then I can still reach the WebUI from port 443, and only get connected from the edgemax products via port 443, and not 8082 which I want to change it too. 

I have not tried changing to 
`docker run -e PUBLIC_WS_PORT=8082 --e PUBLIC_HTTPS_PORT=8082 -p 8082:443 oznu/unms`

If I change to this, I will change the GUI port and inform port to 8082, which I don't want. 
I want to be able to use a serperate port to communicate with my devices, so I don't expose the WebUI right away, but only behind my reverse proxy setup.

**Comment by oznu** [comment]
I've made a change that should help. 

Wait for the build to complete: https://hub.docker.com/r/oznu/unms/tags/. Then pull down the latest version of the image:

```
docker pull oznu/unms
```

This new image allows you to set the ws port the built in nginx server exposes to be something different. The default is 443 which is the same as the GUI server.

```
docker run -p 443:443 -p 9000:9000 -e WS_PORT=9000 -e PUBLIC_WS_PORT=9000 oznu/unms
```

This should match the behaviour of the `--ws-port` option.

Note that the logs will still say the http server and ws server are running on port 8081 and 8082, this is just the ports the node.js process is listening on, the containers nginx service is proxying requests from the `WS_PORT` to 8082. Don't try and and set the `WS_PORT` to  8081 or 8082 as well or else you'll end up with an `EADDRINUSE` error.

**Comment by bjonness406** [comment]
Works perfect now! Thanks for the help.
