### ISSUE TITLE
Stuck in Exporting

### ISSUE THREAD

**Issue by m00tz** [oznu/docker-unms#14]
![off unms](https://user-images.githubusercontent.com/38958790/39594342-4dc6d8fa-4ec1-11e8-9bce-1c271154cccd.jpeg)
I am running this on a DSM Following your steps on setup, It was working, The only thing I have changed recently is my DHCP range and set my DSM to a Link aggregation setup. All my other packages are still working(unifi). It now seems to stuck on Exporting , telling me when I try to login that its starting up , but never does.
![on umns](https://user-images.githubusercontent.com/38958790/39594408-7affddc6-4ec1-11e8-97bf-3ebe07a9b90c.jpeg)
![unms starting](https://user-images.githubusercontent.com/38958790/39594482-a71b4ad0-4ec1-11e8-924f-22e3afe907fe.jpeg)
I checked the logs and its says this "[error] 463#463: *43 connect() failed (111: Connection refused) while connecting to upstream, client: 172.17.0.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082// ... "My server"" Not sure what the means. 
Any help with this issue would be greatly appreciated.

**Comment by Saik0Shinigami** [comment]
I'll give it a go in the help you department. Mind posting the docker command or the docker-compose you're using?

Have you tried killing the container and recreating it? Does it run if you don't use the data directory you already created (fresh image)? Is Unifi also a docker image on this machine, what does it report it's IP as? It's entirely possible that the docker network manager went wonky (the exit side of it would be the 172.17.0.1 address).  You should be able to validate that in the network tab of the DSM docker app or under the network tab in the container details. The error you posted seems like it's a Docker issue more-so than the image causing an issue.
