### ISSUE TITLE
Arm build for 0.12.2 failing

### ISSUE THREAD

**Issue by Saik0Shinigami** [oznu/docker-unms#17]

**Comment by Zaf9670** [comment]
Not sure if you're having the same issues as me or not but I cannot use the docker-compose pull unms command.

I keep getting "ERROR: Get https://registry-1.docker.io/v2/oznu/unms/manifests/armhf: received unexpected HTTP status: 503 Service Unavailable"

**Comment by Saik0Shinigami** [comment]
I'm referencing this.. 
![image](https://user-images.githubusercontent.com/37313164/41824799-882bbe7e-77cb-11e8-80e3-74ade9757ebc.png)

But you're error might be caused by this build failure. Git might not like trying to distribute failing builds.

Edit: My paint skills are terrible and I feel terrible.

**Comment by oznu** [comment]
I'll fix this soon; I'm away from my normal workspace for the next couple weeks.

Happy to accept a PR to resolve the issue in the meantime.

**Comment by Saik0Shinigami** [comment]
Any luck on this? I looked into trying to build it for myself, but I have no idea what I'm doing with docker. I feel like I need to find some videos on this now...

We have ~2 weeks before UNMS 13.0 drops. In case you haven't heard.

**Comment by oznu** [comment]
I'll probably wait for 0.13.0 before dedicating time to fixing this.

There are some Alpine Linux dependency issues in the current build preventing the ARM version from building.

**Comment by Clam-** [comment]
Since the 0.13 alpha is out, I was wondering what plans you had around 0.13. What particular build are you aiming for (alpha, beta, public?) and what things do you need help with for the transition?

Thanks.

**Comment by citgot** [comment]
Hi, are you still developing this? Looks like there’s talk about 0.14 already

**Comment by oznu** [comment]
0.13.0 is now available for armhf and amd64.

**Comment by oznu** [comment]
@Clam- I'm only targeting the public builds. Trying to keep up with the changes in every alpha/beta/rc is too much work.

https://github.com/Ubiquiti-App/UNMS/releases
