### ISSUE TITLE
Connection attempt has failed

### ISSUE THREAD

**Issue by snormonster** [oznu/docker-unms#18]
Not sure why, but I haven't been able to connect my Edgerouter ER-X to UNMS. I am running this container on docker on Synology NAS.

ER-X is on latest firmware 1.10.5, private lan side IP = 192.168.1.1
Docker host IP = 192.168.1.200
UNMS latest, 0.12.2 beta
Running in bridged mode with ports remapped. 

I can: login to UNMS from lan connected PC, inside UNMS I can discover my ER-X, it successfully logs in to the router and adds the wss connection string to ER-X. The ER-X does not connect back so in UNMS it times out and displays: "Connection attempt has failed". I have followed [https://help.ubnt.com/hc/en-us/articles/115015690147-UNMS-Device-Discovery](url) and it seems both devices can see each other.

**Comment by snormonster** [comment]
At one point I grabbed a screenshot of the terminal info, not sure if this error is related
![image](https://user-images.githubusercontent.com/15768839/42476757-31ed6dd6-83cf-11e8-9bb0-a3134edd2599.png)

**Comment by maprambo** [comment]
I've got the same problem. I found the protocol upgrade (websocket) failing. Nginx gives a 502.

**Comment by maprambo** [comment]
I found this is because the container uses ::1 (IPv6 localhost address)for internal traffic even when IPv6 is disabled - as a result, the address can't be reached.

**Comment by mysterfr** [comment]
Hello, same problem here.

Running on Synology DS3617xs with EdgeRouter 4.
Docker host IP : 10.25.0.5
ER4 : 10.25.0.2, FW v1.10.8
UNMS : v0.13.1

Docker ports : Local/container
```
2055/2055 (UDP/Netflow)
8443/443
```

ENV :
```
WS_PORT : 8443 (also tried with 443)
PUBLIC_WS_PORT:8443
PUBLIC_HTTPS_PORt:8443
```

When looking at the ER4 logs, I get :
```
2019-01-03 01:02:21 ERROR connection error (10.25.0.5:8443): HS: ws upgrade response not 101
2019-01-03 01:02:41 ERROR connection error (10.25.0.5:8443): HS: ws upgrade response not 101
2019-01-03 01:03:01 ERROR connection error (10.25.0.5:8443): HS: ws upgrade response not 101
```

I tried the HTTPS WebSocket test described [here](https://help.ubnt.com/hc/en-us/articles/115015690147-UNMS-Device-Discovery#4), and I do not get the expected results at all : I get an HTML doc instead of the websocket upgrade header.

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 03 Jan 2019 00:12:03 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 5211
Connection: keep-alive
vary: origin,accept-encoding
access-control-allow-origin: http://example.com:80
access-control-expose-headers: x-auth-token
cache-control: no-cache
accept-ranges: bytes
strict-transport-security: max-age=15768000
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-xss-protection: 1; mode=block
feature-policy: camera 'none'; microphone 'none'; magnetometer 'none'; gyroscope 'none'; speaker 'none'; vibrate 'none'; payment 'none'
Referrer-Policy: same-origin
Content-Security-Policy: default-src 'self' data: wss: api.github.com *.tile.openstreetmap.org *.gstatic.com *.googleapis.com; style-src 'self' 'unsafe-inline' *.googleapis.com;

<!doctype html><html lang="en"><head><title>UNMS 0.13.1</title><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="apple-itunes-[...]

```
Let me know if you need anything more.

**Comment by mysterfr** [comment]
Nevermind... forget about my previous post.

I deleted the container, started fresh (except for config files as I left the mounted volume untouched).
I ended up fiddling into the UNMS settings, and made the following changes:
- First created an A record on my internal DNS server, such as "unms.localdomain.local" pointing to my NAS' IP address
- then in UNMS settings : 
    * UNMS/UNMS Hostname/IP : replaced the IP address with a DNS record
    * UNMS/Date format : changed to ISO (YYYY-MM-DD), not sure this makes any difference
    * Devices/Ping address : put the DNS name instead of the NAS' IP address

A few seconds after having saved these settings, my ER4 poped into the "Devices" view, waiting to be accepted....
