### ISSUE TITLE
Build fails on openssl apk packages

### ISSUE THREAD

**Issue by agherzan** [oznu/docker-unms#19]
There seem to be no openssl-* packages but only openssl1.0-* as reported by the build. I haven't investigated further but here is the error:

```
[unms]      ERROR: unsatisfiable constraints:
[unms]      
[unms]        openssl-dev (virtual):
[unms]          provided by: openssl1.0-dev
[unms]          required by: world[openssl-dev]
```

**Comment by oznu** [comment]
Thanks @agherzan  - that's what is causing the ARM build to fail here: https://github.com/oznu/docker-unms/issues/17

I'll be fixing all this up once ubnt release unms 0.13.0.

**Comment by agherzan** [comment]
@oznu The annoying bit is that even if I fixed the build error by using the new package name, the container fails now at runtime with undefined symbol error. So I think this is a little more complicated than just this specific error.
