### ISSUE TITLE
Internal Server Error When Reverse Proxying with Traefik

### ISSUE THREAD

**Issue by seffyroff** [oznu/docker-unms#20]
Hi there!

Thanks for making this container, it should make managing the UNMS deployment far easier (once I have got it working!).

I'm seeing internal server error when I try to hit UNMS from my reverse proxy.  I wonder if some of the services in your container require ports mapping?  I'm running in Docker Swarm mode, with your container attached to an overlay network, which usually means all ports are exposed without mapping anything.   Service labels are set for Traefik to read, and configure the FE>BE routing.  It's set to map the FE to port 443 on your container, and to use HTTPS.

I've set your container env vars for WS_PORT, PUBLIC_WS_PORT and PUBLIC_HTTPS_PORT all to be 443.

If I map ports to the container host, I'm able to reach the UNMS interface from the LAN.

**Comment by danteali** [comment]
Had the same issue. Tried all sorts of combinations of Traefik labels but couldn't get it working.

Ended up explicitly defining a backend/frontend pair in traefik.toml which works without any issues. There are a couple of services I've had to do this for since the Traefik labels haven't worked (e.g. Nextcloud, Unifi Controller).

**Comment by xGlorify** [comment]
@danteali Would you have an example of that .toml file? I'm struggling to get it online behind my Traefik reverse proxy as well.

**Comment by danteali** [comment]
> @danteali Would you have an example of that .toml file? I'm struggling to get it online behind my Traefik reverse proxy as well.

Yeah, no problem. Just add the following to your traefik.toml file in the backend and frontend sections, point the backend at your internal UNMS address and port (I changed my UNMS port to 8040)...
```
[backends]
  [backends.unms]
    [backends.unms.servers]
      [backends.unms.servers.server1]
      url = "https://192.168.0.10:8040/"

[frontends]
  [frontends.unms]
  backend = "unms"
  passHostHeader = true
    [frontends.unms.routes]
      [frontends.unms.routes.route1]
      rule = "Host:unms.domain.com"
```
Defining frontends and backends like this allows you to use Traefik for any services on your internal network. It's really handy. Even though UNMS, and pihole docker containers run on the same server with Traefik, this was the only way I could expose them for external access. The labels wouldn't work for me. 

Also remember that you can add authentication to the services exposed through Traefik like this. For example, pihole doesn't really have any authentication for it's admin page (UNMS has it's own username/password page) so you can add basic authentication by adding these lines to the [frontend] section...
```[frontends]
  [frontends.pihole]
  backend = "pihole"
  passHostHeader = true
    [frontends.pihole.routes]
      [frontends.pihole.routes.route1]
      rule = "Host:pihole.domain.com"
    [frontends.pihole.auth.basic]
      removeHeader = true
      users = ["<username>:<password hash>"]
```
Generate the password hash with: 
`htpasswd -nb <username> '<password>'`
