### ISSUE TITLE
Updating UNMS

### ISSUE THREAD

**Issue by Riaan007** [oznu/docker-unms#22]
I'm new to this game so unit wants to get a clear explanation on updating docker-unms.

I did the following: docker-compose pull unms 
And got the following: Done

but no update still on 0.12.1

also restored, stop and installed it and then restarted it 

Anything I'm missing or is there still no update from 0.12.1?

**Comment by oznu** [comment]
0.13.0 is now available.

**Comment by Riaan007** [comment]
Thanks. 
But still no updated version on my side

Step one: docker-compose pull unms - Done
Step two: ?

I did restarted it also.

**Comment by oznu** [comment]
Run `docker-compose up` after running pull to recreate the container using the new image.

https://github.com/oznu/docker-unms/wiki/UNMS-on-Raspberry-Pi#updating-unms

**Comment by Riaan007** [comment]
Thanks
