### ISSUE TITLE
Update UNMS

### ISSUE THREAD

**Issue by Roberto6969** [oznu/docker-unms#24]
I would like to update UNMS through command line. But whenever I try to update I get message "unms_unms_1 is up-to-date". But it is not because web interface still shows old version. Is there any solution to update UNMS?

![image](https://user-images.githubusercontent.com/21200507/46403755-add44880-c703-11e8-9ac8-b10fd7c6dacc.png)

**Comment by oznu** [comment]
Does your docker-compose.yml specify an image version?

**Comment by Roberto6969** [comment]
Here is content of docker-compose.yml file:

![image](https://user-images.githubusercontent.com/21200507/46414449-6bbaff00-c723-11e8-831b-b438472491d5.png)
