### ISSUE TITLE
Can't find a suitable configuration file in this directory or any parent. Are you in the right directory?

### ISSUE THREAD

**Issue by ralfr** [oznu/docker-unms#27]
I'm running your awesome image on a Synology Disk Station. So far, everything went beautiful. I'm just having difficulties to upgrade.

`docker-compose pull oznu/unms:latest`

yields a

```
Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?
Supported filenames: docker-compose.yml, docker-compose.yaml
```

error. I'm root and in /. Any idea what I've got to do to make it work?

**Comment by ralfr** [comment]
Also: I pulled unms:latest but it apparently doesn't seem to point to the 0.13.0 version?

**Comment by oznu** [comment]
> I'm root and in /. Any idea what I've got to do to make it work?
 
You need to be in the same directory as the `docker-compose.yml` file you created somewhere on your system when setting this up.
