### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by Snotmann** [oznu/docker-unms#29]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@0.13.0 start: `npm run backup:apply && npm run migrate && node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unms-server@0.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

The updated image wont build a working container ...

**Comment by oznu** [comment]
What platform are you running on?

Can you provide more log? The actual error will be further up.

**Comment by Snotmann** [comment]
Sure  ... im using the container at raspberian on my RPI3.

> GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-timezone: executing...
[cont-init.d] 20-set-timezone: exited 0.
[cont-init.d] 40-prepare: executing...
ln: failed to create symbolic link '/www/firmwares/firmwares': File exists
ln: failed to create symbolic link '/cert/cert': File exists
[cont-init.d] 40-prepare: exited 0.
[cont-init.d] 50-postgres: executing...
Database already configured
[cont-init.d] 50-postgres: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting unms-netflow...
Starting nginx...
/tmp:5432 - no response
Waiting for postgres to come up...
Running entrypoint.sh
Will use existing SSL certificate
Entrypoint finished
Calling exec
[services.d] done.
LOG:  could not bind IPv6 socket: Address not available
HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
LOG:  database system was shut down at 2018-11-12 19:52:33 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
FATAL:  database "root" does not exist
/tmp:5432 - accepting connections
Running docker-entrypoint npm start
Waiting for database containers
LOG:  incomplete startup packet
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Listening for netflow packets on port 2055 (70 ms)","time":"2018-11-12T21:32:16.987Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Initializing database","time":"2018-11-12T21:32:16.999Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Database initialized (81 ms)","time":"2018-11-12T21:32:17.080Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Initializing Redis","time":"2018-11-12T21:32:17.082Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Redis initialized (17 ms)","time":"2018-11-12T21:32:17.099Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Initializing RabbitMQ","time":"2018-11-12T21:32:17.108Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":50,"msg":"Failed to connect to RabbitMQ: connect ECONNREFUSED 127.0.0.1:5672","time":"2018-11-12T21:32:17.144Z","v":0}
2018/11/12 21:32:22 [error] 425#425: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"
2018/11/12 21:32:22 [crit] 425#425: *1 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:32:25 [error] 421#421: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.12, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"
2018/11/12 21:32:25 [crit] 421#421: *4 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.12, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:32:26 [error] 425#425: *7 no live upstreams while connecting to upstream, client: 172.16.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://websocket//", host: "172.16.1.254"
2018/11/12 21:32:26 [error] 421#421: *8 no live upstreams while connecting to upstream, client: 172.16.1.11, server: , request: "GET // HTTP/1.1", upstream: "http://websocket//", host: "172.16.1.254"
Background append only file rewriting started
Exec npm start

> unms-server@0.13.0 start /home/app/unms
> npm run backup:apply && npm run migrate && node --max_old_space_size=2048 index.js


> unms-server@0.13.0 backup:apply /home/app/unms
> node ./cli/apply-backup

UNMS BACKUP start
There is no UNMS backup found
UNMS BACKUP finished

> unms-server@0.13.0 migrate /home/app/unms
> node ./cli/migrate.js

Setting database schema version to 0.13.0
Done
2018/11/12 21:32:42 [crit] 421#421: *9 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:32:42 [error] 421#421: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"
{"name":"UNMS","hostname":"165bb4d7b207","pid":783,"level":30,"msg":"Master 783 is running","time":"2018-11-12T21:32:43.247Z","v":0}
2018/11/12 21:32:45 [error] 423#423: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.12, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"
2018/11/12 21:32:45 [crit] 423#423: *12 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.12, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:32:46 [error] 422#422: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"
2018/11/12 21:32:46 [crit] 422#422: *15 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.2, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:32:46 [error] 421#421: *18 no live upstreams while connecting to upstream, client: 172.16.1.11, server: , request: "GET // HTTP/1.1", upstream: "http://websocket//", host: "172.16.1.254"
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"RabbitMQ initialized (30192 ms)","time":"2018-11-12T21:32:47.301Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Subscribed for managed networks change notifications at queue 'settings.networks.changed'","time":"2018-11-12T21:32:47.340Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Subscribed for site IP addresses change notifications at queue 'site.ips.changed'","time":"2018-11-12T21:32:47.363Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.authorized'","time":"2018-11-12T21:32:47.394Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Subscribed for device authorizations at queue 'device.*.settings.changed'","time":"2018-11-12T21:32:47.415Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Subscribed for settings change notifications at queue 'settings.changed'","time":"2018-11-12T21:32:47.435Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Loaded list of managed networks from database (26 ms) [ '10.0.0.0/8',\n  '172.16.0.0/12',\n  '192.168.0.0/16',\n  '100.64.0.0/10' ]","time":"2018-11-12T21:32:47.463Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Determined UNMS IP address '172.16.1.254' (162 ms)","time":"2018-11-12T21:32:47.660Z","v":0}
{"name":"netflow","hostname":"165bb4d7b207","pid":347,"level":30,"msg":"Starting save and aggregation timers","time":"2018-11-12T21:32:47.661Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":783,"level":30,"msg":"Registering plugins","time":"2018-11-12T21:32:48.101Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"level":30,"msg":"Worker 843 started","time":"2018-11-12T21:32:49.956Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:32:57.180Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:32:58.197Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:32:59.203Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:33:00.205Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:33:01.207Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":843,"component":"ws-device-sync","level":30,"status":0,"data":0,"statistics":0,"stations":0,"stationsPrune":0,"interfaces":0,"interfacesPrune":0,"interfacesStatistics":0,"addresses":0,"addressesDelete":0,"msg":"Device sync data","time":"2018-11-12T21:33:02.209Z","v":0}
{"name":"UNMS","hostname":"165bb4d7b207","pid":783,"level":50,"err":{"message":"Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found","name":"Error","stack":"Error: Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found\n    at Object.Module._extensions..node (internal/modules/cjs/loader.js:717:18)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/app/unms/node_modules/sharp/lib/constructor.js:10:15)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/app/unms/node_modules/sharp/lib/index.js:3:15)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/app/unms/lib/api/v2.1/sites/view.js:13:15)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/home/app/unms/lib/api/v2.1/sites/plugin.js:10:20)\n    at Module._compile (internal/modules/cjs/loader.js:688:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)\n    at Module.load (internal/modules/cjs/loader.js:598:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:529:3)\n    at Module.require (internal/modules/cjs/loader.js:636:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.internals.parsePlugin (/home/app/unms/node_modules/glue/lib/index.js:185:23)\n    at manifest.registrations.map (/home/app/unms/node_modules/glue/lib/index.js:113:39)\n    at Array.map (<anonymous>)\n    at steps.push (/home/app/unms/node_modules/glue/lib/index.js:110:58)\n    at Items.serial (/home/app/unms/node_modules/glue/lib/index.js:129:9)\n    at iterate (/home/app/unms/node_modules/items/lib/index.js:36:13)\n    at done (/home/app/unms/node_modules/items/lib/index.js:28:25)\n    at steps.push (/home/app/unms/node_modules/glue/lib/index.js:101:13)\n    at Items.serial (/home/app/unms/node_modules/glue/lib/index.js:129:9)\n    at iterate (/home/app/unms/node_modules/items/lib/index.js:36:13)\n    at done (/home/app/unms/node_modules/items/lib/index.js:28:25)\n    at steps.push (/home/app/unms/node_modules/glue/lib/index.js:92:9)\n    at Items.serial (/home/app/unms/node_modules/glue/lib/index.js:129:9)\n    at iterate (/home/app/unms/node_modules/items/lib/index.js:36:13)\n    at done (/home/app/unms/node_modules/items/lib/index.js:28:25)\n    at steps.push (/home/app/unms/node_modules/glue/lib/index.js:74:13)\n    at Items.serial (/home/app/unms/node_modules/glue/lib/index.js:129:9)\n    at iterate (/home/app/unms/node_modules/items/lib/index.js:36:13)\n    at Object.exports.serial (/home/app/unms/node_modules/items/lib/index.js:39:9)\n    at Object.exports.compose (/home/app/unms/node_modules/glue/lib/index.js:127:11)\n    at Promise (/home/app/unms/node_modules/glue/lib/index.js:51:21)\n    at new Promise (<anonymous>)\n    at Object.exports.compose (/home/app/unms/node_modules/glue/lib/index.js:49:16)\n    at MergeMapSubscriber.Observable.defer.do.mergeMap [as project] (/home/app/unms/application.js:191:26)\n    at MergeMapSubscriber._tryNext (/home/app/unms/node_modules/rxjs/operators/mergeMap.js:122:27)\n    at MergeMapSubscriber._next (/home/app/unms/node_modules/rxjs/operators/mergeMap.js:112:18)\n    at MergeMapSubscriber.Subscriber.next (/home/app/unms/node_modules/rxjs/Subscriber.js:89:18)\n    at DoSubscriber._next (/home/app/unms/node_modules/rxjs/operators/tap.js:88:30)\n    at DoSubscriber.Subscriber.next (/home/app/unms/node_modules/rxjs/Subscriber.js:89:18)\n    at DeferSubscriber.OuterSubscriber.notifyNext (/home/app/unms/node_modules/rxjs/OuterSubscriber.js:19:26)\n    at InnerSubscriber._next (/home/app/unms/node_modules/rxjs/InnerSubscriber.js:23:21)\n    at InnerSubscriber.Subscriber.next (/home/app/unms/node_modules/rxjs/Subscriber.js:89:18)\n    at MergeMapSubscriber.notifyNext (/home/app/unms/node_modules/rxjs/operators/mergeMap.js:145:30)\n    at InnerSubscriber._next (/home/app/unms/node_modules/rxjs/InnerSubscriber.js:23:21)\n    at InnerSubscriber.Subscriber.next (/home/app/unms/node_modules/rxjs/Subscriber.js:89:18)\n    at /home/app/unms/node_modules/rxjs/util/subscribeToResult.js:37:29\n    at process._tickCallback (internal/process/next_tick.js:68:7)"},"msg":"Unexpected error in master process","time":"2018-11-12T21:33:02.371Z","v":0}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unms-server@0.13.0 start: `npm run backup:apply && npm run migrate && node --max_old_space_size=2048 index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unms-server@0.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/app/.npm/_logs/2018-11-12T21_33_02_450Z-debug.log
FATAL:  database "root" does not exist
/tmp:5432 - accepting connections
Running docker-entrypoint npm start
Waiting for database containers
LOG:  incomplete startup packet
NOTICE:  extension "timescaledb" does not exist, skipping
DROP EXTENSION
Background append only file rewriting started
Exec npm start
2018/11/12 21:33:02 [crit] 423#423: *19 connect() to [::1]:8082 failed (99: Address not available) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://[::1]:8082//", host: "172.16.1.254"
2018/11/12 21:33:02 [error] 423#423: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 172.16.1.1, server: , request: "GET // HTTP/1.1", upstream: "http://127.0.0.1:8082//", host: "172.16.1.254"

**Comment by oznu** [comment]
Thanks. I can confirm this result when testing on my Pi.

It's not looking good. One of UNMS' deps, `sharp`, is not playing nice on musl libc arm.

I'm going to try swapping the base container to Debian, which should solve the musl libc problem.

In the mean time, if you need to get back up and running, I would recommend using one of the older tagged versions of the image.

**Comment by oznu** [comment]
Hi @Snotmann,

Could you give the `debian-armhf` tag a go and let me know if this solves the problem. I have it working on my Pi here.

```
docker run oznu/unms:debian-armhf
```

**Comment by Snotmann** [comment]
Ok its working fine now .. .thanks !!!

**Comment by pr3mi3r3** [comment]
@oznu:
Please edit the readme file with the new image file. New users will be confused with debian-armhf and armhf

**Comment by oznu** [comment]
Thanks for testing.

The Debian tag was just while I got feedback. Once merged into master the tags will remain the same (latest, armhf).

Support for armv6 will be dropped, but I don't think UNMS would be running very well on a Raspberry Pi 1 anyway. Raspberry Pi 2 and higher (armv7) are supported.

**Comment by pr3mi3r3** [comment]
All right, my test was also successful. :-)
I will change back to armhf after merging.
One more thing:
Can you provide 0.13.1-alpha.1?
Unms has introduced important bugfixes and I am not shure when they release the next stable version.

**Comment by oznu** [comment]
0.13.1 and debian are now in master.

**Comment by conradKE** [comment]
yooo bro @oznu  what about UCRM can make it support amrhf kindly please or what are the procedures

**Comment by azim254** [comment]
> Hi @Snotmann,
> 
> Could you give the `debian-armhf` tag a go and let me know if this solves the problem. I have it working on my Pi here.
> 
> ```
> docker run oznu/unms:debian-armhf
> ```

works like charm
