### ISSUE TITLE
Failing to connect to smtp.gmail.com for email notifications

### ISSUE THREAD

**Issue by Peppernip** [oznu/docker-unms#33]
Hello,

Im having an issue with unms just giving me a generic failure when setting up the smtp feature in the UNMS contoller. Has anyone else had this issue?

Thanks,
Peppernip

**Comment by Peppernip** [comment]
I also went thru the whole process from square one again, deleted docker and everything associated with it and what was contained within it and unms, and I still cant connect to any smtp servers.

**Comment by slally** [comment]
There are lots of knobs to twiddle on the Google side of things.  You have 2fa setup?  Did you generate an app password on the Google side?

**Comment by Peppernip** [comment]
I have the account set up and working in unifi, No 2fa no app password needed for unifi to use it, I also have unms set up on my x64 intel server and the email acct just works.
________________________________
