### ISSUE TITLE
[Windows] FATAL:  data directory "/config/postgres" has wrong ownership

### ISSUE THREAD

**Issue by jonnypage-d3** [oznu/docker-unms#34]
Created the container, set the config dir to an empty dir, and on startup I get 

```
Starting postgres...
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
FATAL:  data directory "/config/postgres" has wrong ownership
HINT:  The server must be started by the user that owns the data directory.
```

files do get created.

On Docker for windows 2.0.0.0-win81 on Server 2016 w/ kitematic

**Comment by geoffmyers** [comment]
I am experiencing the same issue with Ubuntu 18.10, Docker 18.06.1-ce, and oznu/unms:latest.

```
Starting postgres...
postgres: could not access directory "/config/postgres": Permission denied
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
```

The above message is in an infinite loop. I tried changing the ownership of the /config directory from the host to 1000:1000 (the "unms" user/group ID) but as soon as the container starts, the ownership of the /config directory is changed to 911:911 (the "abc" user/group ID).

**Comment by djismgaming** [comment]
> I am experiencing the same issue with Ubuntu 18.10, Docker 18.06.1-ce, and oznu/unms:latest.
> 
> ```
> Starting postgres...
> postgres: could not access directory "/config/postgres": Permission denied
> /var/run/postgresql:5432 - no response
> Waiting for postgres to come up...
> ```
> 
> The above message is in an infinite loop. I tried changing the ownership of the /config directory from the host to 1000:1000 (the "unms" user/group ID) but as soon as the container starts, the ownership of the /config directory is changed to 911:911 (the "abc" user/group ID).

Did you encounter a fix for this? I have the same issue on Debian Stretch

**Comment by geoffmyers** [comment]
If I remember correctly, I believe I had to perform a fresh reinstall with new directory/volume mappings, which "fixed" the problem. I exported the UNMS settings before and then reimported them after.
