### ISSUE TITLE
Changing Port

### ISSUE THREAD

**Issue by majorpaynedof** [oznu/docker-unms#36]
I added -p 85:85 -p 445:445

and I'm unable to get to the website I get the following errors
`[
    {
        "Id": "91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401",
        "Created": "2019-01-31T19:43:25.644172796Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 23190,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-01-31T19:43:25.979544077Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:838918070999ddf382a2d21b1a13f0c1f48a3f50aa26fb408c9c5fff2b808f42",
        "ResolvConfPath": "/var/lib/docker/containers/91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401/hostname",
        "HostsPath": "/var/lib/docker/containers/91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401/hosts",
        "LogPath": "/var/lib/docker/containers/91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401/91de77edd92a3a5cca584e03628e2990e07a67967144a6a7d6248c927dd3b401-json.log",
        "Name": "/UNMS",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/etc/localtime:/etc/localtime:ro",
                "/sharedfolders/appdata/UNMS:/config:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {
                "8082/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8082"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/7bfa4839ae827682ec4a810f51ab7ea955d070332d140572e8a1d8fdda321ad8-init/diff:/var/lib/docker/overlay2/4617aecbdd83a8e483c551504e474dd85b5dbc9bdd4a08e5df33ddf5a31eda67/diff:/var/lib/docker/overlay2/c26e5875934b34ec22c49c189cd14b8c1a799577c3ec594f0892f1e697d08a82/diff:/var/lib/docker/overlay2/3258ec4055d88ddcdcd308f6d1ae2e981d385a012d1498d8f016d1f24c381d06/diff:/var/lib/docker/overlay2/c9faf0a9f539ab20fd90a1848554474a6b20cdee2229b2e4f215a5cbf132fdd0/diff:/var/lib/docker/overlay2/1eadf72da200edf2834325ee9c60c04c1c0c02c991df91aa8aa10b70b924f929/diff:/var/lib/docker/overlay2/c6dc158b0338f9bc8643d94de6800ac25a3762243d415265e939cd6fb42e8316/diff:/var/lib/docker/overlay2/f8e26b65369476f25afadeb1702319cf8f8a97edd9d4cffdc0d91140234b80fe/diff:/var/lib/docker/overlay2/86e8bd8af6fabc538dae1cd1e57cc8dbaeff715e9b2aca89eb6df7f70902f9b5/diff:/var/lib/docker/overlay2/268932ed58164e68c489f6d479c2fc7f4c5512a7ac75c86a51b50cb7b78c29ef/diff:/var/lib/docker/overlay2/83fe7dd5d2bc817d32236a2dde8b33adfa57c2afe12cea8a8a96f22a53af43bf/diff:/var/lib/docker/overlay2/cc7a0863b05905502adf7001794ae107196f4bf425d957f33a632f37b291cb32/diff:/var/lib/docker/overlay2/ebfa8f74770dd1eb47579eee9ba1ed22d51b81c0098427f5825bdf41f69caf4f/diff:/var/lib/docker/overlay2/ecb87bd2a673dce9ee286db6331daddf4999341175337770e2858e342a52a29b/diff:/var/lib/docker/overlay2/d2a1a2391c1d8f10d989de56753bb31466738fbedae63039318b7a24300add4b/diff:/var/lib/docker/overlay2/ce96221513a265c980b938e3d70e8231d7ae5f12ad7bc26f9e1d33ea18fc35bd/diff:/var/lib/docker/overlay2/d42f3d4e735fe3377bd3b3686636980feed567738c222f8a9481315d9bc24e27/diff:/var/lib/docker/overlay2/e6cab56dcff9e586b04a66eccae8a703282bceb9c875fb315b40137d3023d30f/diff:/var/lib/docker/overlay2/bc371ed16050f5bc2856f7cd8012380bd3c269339fdcbecfc70ea77729188d11/diff:/var/lib/docker/overlay2/9e7dbda24293fc203def7517a2defe1c19930c59e48fef47be1c3a71591d5d61/diff:/var/lib/docker/overlay2/a6a542856ad33c77f6d05952b1595fa5343ef57b804c24f37f3d88096536b169/diff",
                "MergedDir": "/var/lib/docker/overlay2/7bfa4839ae827682ec4a810f51ab7ea955d070332d140572e8a1d8fdda321ad8/merged",
                "UpperDir": "/var/lib/docker/overlay2/7bfa4839ae827682ec4a810f51ab7ea955d070332d140572e8a1d8fdda321ad8/diff",
                "WorkDir": "/var/lib/docker/overlay2/7bfa4839ae827682ec4a810f51ab7ea955d070332d140572e8a1d8fdda321ad8/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/etc/localtime",
                "Destination": "/etc/localtime",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/sharedfolders/appdata/UNMS",
                "Destination": "/config",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "Plexserver",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "2055/udp": {},
                "443/tcp": {},
                "80/tcp": {},
                "8082/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "SSL_CERT=",
                "YARN_VERSION=1.12.3",
                "PATH=/home/app/unms/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/9.6/bin",
                "DEBIAN_FRONTEND=noninteractive",
                "NGINX_VERSION=nginx-1.12.2",
                "NGINX_UID=1000",
                "LUAJIT_VERSION=2.1.0-beta3",
                "S6_KEEP_ENV=1",
                "PGID=100",
                "WS_PORT=443",
                "QUIET_MODE=0",
                "PUBLIC_WS_PORT=443",
                "UNMS_NETFLOW_PORT=2055",
                "PUID=1000",
                "QEMU_ARCH=x86_64",
                "PGDATA=/config/postgres",
                "NODE_VERSION=10.15.0",
                "POSTGRES_DB=unms",
                "LUA_NGINX_VERSION=0.10.13",
                "PUBLIC_HTTPS_PORT=443",
                "SECURE_LINK_SECRET=enigma"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "oznu/unms:latest",
            "Volumes": {
                "/config": {}
            },
            "WorkingDir": "/home/app/unms",
            "Entrypoint": [
                "/init"
            ],
            "OnBuild": null,
            "Labels": {
                "omv_docker_extra_args": "-p 8082:8082"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e754de17a460d031b36bf13f5969e041ad2b9af528c4b8e1cb0706f67a179636",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "250fcf67cdc993b4b3cc0956251c751a1b7435f1b50b79622348861fe6259a70",
                    "EndpointID": "ff6ec9854a6c8f925d08c440e7c04c6ec369425c7750ad966bfe60cf3495e052",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]`

**Comment by oznu** [comment]
You would need something like this:

```
-p 85:80 -p 445:443 -e PUBLIC_HTTPS_PORT=445  -e PUBLIC_WS_PORT=445 
```

See https://github.com/oznu/docker-unms#parameters
