### ISSUE TITLE
0.13.3 image in docker hub

### ISSUE THREAD

**Issue by aacebedo** [oznu/docker-unms#39]
Hi !
Great work on this ! It is working perfectly on my infrastructure.
Do you know if it is possible to trigger a build for the 0.13.3 version of unms and push it to docker hub ?

Thanks !

**Comment by Aleson72** [comment]
Please add working LE to version 0.13.3

https://community.ubnt.com/t5/UNMS-Beta/Letsencrypt-quot-can-only-be-used-for-FQDN-quot/m-p/2653235#M11047

**Comment by oznu** [comment]
Latest image is now 0.13.3. I'll push a tagged release soon.

**Comment by aacebedo** [comment]
Thank you !
