### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by GreenUkr** [oznu/docker-unms#4]
Thank you for your perfect job.
It's working fine on my synology DS1515+ nas in doker.
Only 1 issue I found is a friquent logging. I seem it set debug mode. Any chance to edit it to lower?

**Comment by oznu** [comment]
Looking at the UNMS code, the app is just using a wrapper around `console.log`, which is a built in JavaScript/Node.js function. There is no way, without of modifying the code, to adjust the log level as far as I can tell. This could be intentional as the product is still in "beta" and Ubiquiti wants to get as much debug data from users as possible when they encounter errors.

Here is the relevant file from UNMS source `./lib/logging/index.js` v0.11.0:

```js
'use strict';

const { exec } = require('child-process-promise');
const serializeError = require('serialize-error');

const config = require('../../config');

let logFunc = console.log;

function log(...args) {
  logFunc(...args);
}

const debug = (...args) => log('debug', ...args);
const info = (...args) => log('info', ...args);

function error(data, err = null, timestamp = null) {
  let payload;
  if (!data) {
    payload = {};
  } else if (data instanceof Object) {
    payload = data;
  } else {
    payload = { message: data };
  }

  if (err) payload.error = serializeError(err);

  log('error', payload, timestamp);
}

function setLogFunction(logFunction) {
  logFunc = logFunction;
}

const packLogs = (outputDir) => {
  debug('Packing logs...');
  const promise = exec(`find ${config.logs.dir} -type f -exec basename {} ';' \
    | xargs -r tar -C ${config.logs.dir} -czf ${outputDir}/${config.logs.packageName}`)
      .catch((err) => {
        error({ outputDir, message: 'Failed to pack log files.' }, err);
        throw err;
      });

  const childProcess = promise.childProcess;
  childProcess.stderr.on('data', err => error('ChildProcess stdout: Failed to pack log files.', err));
  return promise;
};

module.exports = {
  setLogFunction,
  log,
  error,
  debug,
  info,
  packLogs,
};
```

**Comment by Chaz6** [comment]
Is is possible to use a shim to mitigate this behavior? It is causing the host messages log to balloon like crazy.

**Comment by oznu** [comment]
@Chaz6, the logs currently get saved to a file (to fix https://github.com/oznu/docker-unms/issues/3) and sent to stdout, I'll implement an option to prevent logs being sent to stdout soon which should mitigate the issues you are having.

I'll also investigate adding logrotate to the log file I'm saving to disk.

**Comment by Chaz6** [comment]
Great thank you!

**Comment by oznu** [comment]
@Chaz6 

I've added this in the latest image. The verbose logging can be suppressed using the `QUIET_MODE=1` env var.

```
docker run -e QUIET_MODE=1 oznu/unms
```

Logs are still saved to disk, and if UNMS exits with an error, the last 100 lines will be displayed in the Docker logs to help debug.

**Comment by GreenUkr** [comment]
Super. Thank you very much.
You are the best

Best regards,
Gennadiy Vasylkov

**Comment by Chaz6** [comment]
Excellent thank you @oznu !
