### ISSUE TITLE
Error when installing docker-compose

### ISSUE THREAD

**Issue by drtweak** [oznu/docker-unms#45]
When installing Docker Compose using the following line

sudo apt-get -y install python-setuptools && sudo easy_install pip  && sudo pip install docker-compose

and also using other install methods I get the following error. 

Command "/usr/bin/python /usr/local/lib/python2.7/dist-packages/pip-19.0.3-py2.7.egg/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-rdnEhr/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools wheel "cffi>=1.4.1; python_implementation != 'PyPy'"" failed with error code 1 in None

Not sure where to go from here. Everything goes well up to this point. Clean install of Raspbian Stretch Lite.

**Comment by oznu** [comment]
Try this:

```
sudo apt-get -y install python-setuptools && sudo easy_install pip  && sudo pip install docker-compose~=1.23.0
```

The lastest release of docker-compose added some new deps.

**Comment by drtweak** [comment]
BOOM that was it! Thanks!
