### ISSUE TITLE
Instalation on Raspberry PI ZERO

### ISSUE THREAD

**Issue by testJSON1** [oznu/docker-unms#47]
I installed UNMS container on a PI ZERO (ARMV6) . Installation was smooth.  No errors of any kind.  However when I tried to connect through a browser I got nothing.  Both on HTTP and also HTTPS.
Connecting with curl I got Connection reset by peer.  Is this image suppose to work on ARMV6 ?

**Comment by oznu** [comment]
Hi @testJSON1,

This image is built against Debian arm32v7 image - it's not likely to run on a arm32v6 device.

**Comment by testJSON1** [comment]
Thank You for the answer.  This explains the behavior.  Is there any previous version built for ARMV6?

**Comment by oznu** [comment]
This was the last release to support ARMv6, based on Alpine Linux:

https://github.com/oznu/docker-unms/releases/tag/0.13.0r3

Debian was easier to get some bits working consistently, and Debian only targets ARMv5 and ARMv7. As Node.js does not provide prebuilt binaries for ARMv5, I had to pick ARMv7.
