### ISSUE TITLE
Clear huge unms.log

### ISSUE THREAD

**Issue by Roberto6969** [oznu/docker-unms#48]
My unms.log is huge - 11 GB.
![image](https://user-images.githubusercontent.com/21200507/58454186-eb1b9980-811d-11e9-9e33-e28030327d63.png)

 Is it possible to:
1) manually clear log
2) automatically compress (or clear) log as it is in official installation? (https://community.ubnt.com/t5/UNMS-Beta/Manually-Clear-Logs-in-UNMS/td-p/2713276)

Otherwise project works fantastic - thank you!

**Comment by oznu** [comment]
This should be happening with logrotate inside the container:

https://github.com/oznu/docker-unms/blob/master/root/etc/logrotate.d/unms

I'll check it's all working when I do the 0.14.0 release, I did have an issue with the permissions on the logrotate job in one of my other containers which prevented the cron from running.

**Comment by Roberto6969** [comment]
Just to point to the right cause: in my logrotate.d is no trace of unms. Should be something there?  
![image](https://user-images.githubusercontent.com/21200507/58454865-11423900-8120-11e9-8806-574c6f33aa93.png)

**Comment by oznu** [comment]
From the screenshot you've run the `ls -l` command on the host, not inside the container?

If I'm mistaken you may just be running an older version of the container?

**Comment by Roberto6969** [comment]
Yes, you're right - I think this is the right content
root@af1a6ebc3f07:/etc/logrotate.d# ls -l
total 36
-rw-r--r-- 1 root root 173 Sep 13  2017 apt
-rw-r--r-- 1 root root  82 May 26  2018 certbot
-rw-r--r-- 1 root root 232 Jun 26  2018 dpkg
-rw-r--r-- 1 root root 146 Feb 10  2018 exim4-base
-rw-r--r-- 1 root root 126 Feb 10  2018 exim4-paniclog
-rw-r--r-- 1 root root 173 Jun  8  2018 postgresql-common
-rw-r--r-- 1 root root 260 Dec 29  2016 rabbitmq-server
-rw-r--r-- 1 root root 124 Jun 18  2018 redis-server
-rw-rw-r-- 1 root root 104 Feb 21 12:06 unms
root@af1a6ebc3f07:/etc/logrotate.d#

And this is my unms:
root@af1a6ebc3f07:/etc/logrotate.d# cat unms
/config/unms/logs/*.log {
  size 10M
  copytruncate
  missingok
  rotate 7
  compress
  delaycompress
}root@af1a6ebc3f07:/etc/logrotate.d#

**Comment by oznu** [comment]
If you chmod that unms file to `644` that should fix it until the next release.

You might want to manually delete the 11gb file though.

**Comment by Roberto6969** [comment]
Done - thank you!
