### ISSUE TITLE
Letsencrypt setup doesn't work

### ISSUE THREAD

**Issue by agherzan** [oznu/docker-unms#8]
When validating the host, letsencrypt uses a challenge key over http/80. That port is already occupied by fluentd so the auth fails with 

> The client lacks sufficient authorization :: Invalid response from 

I only need this ones until I setup the certificate. Renewal doesn't need this afterwards. Any idea how to temporary move fluentd on another port?

**Comment by oznu** [comment]
Hi @agherzan,

The container does not run fluentd, the environment variable that is set is just to "trick" unms into thinking it's online so you don't errors in the log. More info here: https://github.com/oznu/docker-unms/issues/1.

As for the Let't Encrypt issue, I have tested this on the latest beta version of the container and it works. You can switch to this version by using the `0.12.0-beta.7` tag.

amd64:

```
docker run oznu/unms:0.12.0-beta.7
```

arm:

```
docker run oznu/unms:0.12.0-beta.7-armhf
```

**Comment by agherzan** [comment]
I updated the image but still no success. What was your port configuration? What did you expose outside for letsencrypt auth to go through? I can't get rid of:

```
Timestamp: Today at 12:41
Error: Failed authorization procedure. XXX (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://XXX: \"<html>\r {br} <head><title>404 Not Found</title></head>\r {br} <body bgcolor=\"white\">\r {br} <center><h1>404 Not Found</h1></center>\r {br} <hr><center>\" {br} {br}
```

**Comment by oznu** [comment]
You'll need to be exposing port 80 to the internet. Let's  Encrypt won't use any other port to verify when using the http-01 verification method.

```
docker run -p 80:80 -p 443:443  oznu/unms:0.12.0-beta.7
```

**Comment by agherzan** [comment]
I did that but with no success. I dropped the idea to do it from UNMS and I'm doing it directly through synology's reverse proxy.
