### ISSUE TITLE
Process Owners

### ISSUE THREAD

**Issue by buckaroogeek** [oznu/docker-unms#9]
Not sure if this is an issue or not. This is what I use to start oznu/docker-unms:

docker run -p 80:80 -p 443:443 -e TZ=America/Pacific -e PUID=$uUID -e PGID=$uGID
 -v $PWD/config:/config:Z --name unms oznu/unms:latest

where
uUID=$(id -u)
uGID=$(id -g)

when I look in the config directory I see:
[bgsmith@pico config]$ ll
total 16
drwxr-xr-x.  5 nobody  nobody  4096 Mar 23 09:38 logs
drwx------. 19 avahi   avahi   4096 Mar 23 09:38 postgres
drwxr-xr-x.  2 bgsmith bgsmith 4096 Mar 23 09:38 redis
drwxr-xr-x. 10 bgsmith bgsmith 4096 Mar 23 09:38 unms

Should logs be set to user nobody and postgres to avahi?

thanks

brad

**Comment by oznu** [comment]
Hi @buckaroogeek,

This is a bit hard to explain without explaining how linux containers work. What you're seeing is just a side effect of the users inside the container using a UID that happens to be the same as an existing user on the host.

If you run this you will see the correct owners (with `bgsmith` replaced with `abc`):

```
docker exec -it unms ls -la
```

Or if you run this you'll see all the processes running inside the container and the corresponding users:

```
docker exec -it unms ps aux
```

What you're seeing is perfectly normal. Hope this helps.

**Comment by buckaroogeek** [comment]
Thanks for the response. I had been assuming that setting PGID and PUID would apply to all processes in the container that are writing to the data volume and not just some of them.  Perhaps a clarifying statement in the documentation section on User/Group Identifiers would be helpful to others?

Thank you for providing this repackaging of UNMS. I use fedora and this just works like I would expect a docker container to work.

**Comment by oznu** [comment]
I've actually removed the PGID and PUID options from the next version of the container as they were making this image harder to maintain and required more effort to keep up with the regular updates from Ubiquiti.

https://github.com/oznu/docker-unms/tree/0.12.0-beta.7
